package com.cpw.sqlview.sqlview.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class StmDeviceinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.ORGID
     *
     * @mbg.generated
     */
    private String orgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.IP
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.MAC
     *
     * @mbg.generated
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DEV_LONG
     *
     * @mbg.generated
     */
    private String devLong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DEV_LAT
     *
     * @mbg.generated
     */
    private String devLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.MODEL
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.STOPDATE
     *
     * @mbg.generated
     */
    private String stopdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.WARRANTYDATE
     *
     * @mbg.generated
     */
    private String warrantydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DEV_STATE
     *
     * @mbg.generated
     */
    private String devState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DISABLE_REASON
     *
     * @mbg.generated
     */
    private String disableReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.MAINTENANCEMAN
     *
     * @mbg.generated
     */
    private String maintenanceman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.MAINTENANCEPHONE
     *
     * @mbg.generated
     */
    private String maintenancephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.MAINTENANCEPWD
     *
     * @mbg.generated
     */
    private String maintenancepwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.PASSCODE
     *
     * @mbg.generated
     */
    private Short passcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.TELLERID
     *
     * @mbg.generated
     */
    private String tellerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.TELLERNAME
     *
     * @mbg.generated
     */
    private String tellername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.LMK
     *
     * @mbg.generated
     */
    private String lmk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.REMARK1
     *
     * @mbg.generated
     */
    private String remark1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.TMK
     *
     * @mbg.generated
     */
    private String tmk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.PIK
     *
     * @mbg.generated
     */
    private String pik;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.MAK
     *
     * @mbg.generated
     */
    private String mak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.TRADE_SESSION
     *
     * @mbg.generated
     */
    private String tradeSession;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.IS_CLEANING
     *
     * @mbg.generated
     */
    private String isCleaning;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.CASH_ERROR
     *
     * @mbg.generated
     */
    private String cashError;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DEVICE_TYPE
     *
     * @mbg.generated
     */
    private String deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.HSM_ID
     *
     * @mbg.generated
     */
    private Short hsmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.MASK
     *
     * @mbg.generated
     */
    private String mask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.GATE_WAY
     *
     * @mbg.generated
     */
    private String gateWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DEV_OID
     *
     * @mbg.generated
     */
    private String devOid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DEV_STATUS
     *
     * @mbg.generated
     */
    private String devStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.CASH_ERROR_MSG
     *
     * @mbg.generated
     */
    private String cashErrorMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.LMK_TIME
     *
     * @mbg.generated
     */
    private String lmkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.CASH_CYCLE
     *
     * @mbg.generated
     */
    private BigDecimal cashCycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.ONLINE_DATE
     *
     * @mbg.generated
     */
    private String onlineDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.ONLINE_TIME
     *
     * @mbg.generated
     */
    private String onlineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.G_SYS_ID
     *
     * @mbg.generated
     */
    private String gSysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.ZEROBILL_BOX
     *
     * @mbg.generated
     */
    private String zerobillBox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.SOCIAL_NO
     *
     * @mbg.generated
     */
    private String socialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.DEV_GRAY
     *
     * @mbg.generated
     */
    private String devGray;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.LOCKED
     *
     * @mbg.generated
     */
    private String locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.CASHBOX_DEPOSIT
     *
     * @mbg.generated
     */
    private String cashboxDeposit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.CASHBOX_WITHDRAWAL
     *
     * @mbg.generated
     */
    private String cashboxWithdrawal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.CASHBOX_OPTION
     *
     * @mbg.generated
     */
    private String cashboxOption;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_DEVICEINFO.CASHBOX_CHANGE_BFADD
     *
     * @mbg.generated
     */
    private String cashboxChangeBfadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.ID
     *
     * @return the value of STM_DEVICEINFO.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.ID
     *
     * @param id the value for STM_DEVICEINFO.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.ORGID
     *
     * @return the value of STM_DEVICEINFO.ORGID
     *
     * @mbg.generated
     */
    public String getOrgid() {
        return orgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.ORGID
     *
     * @param orgid the value for STM_DEVICEINFO.ORGID
     *
     * @mbg.generated
     */
    public void setOrgid(String orgid) {
        this.orgid = orgid == null ? null : orgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.IP
     *
     * @return the value of STM_DEVICEINFO.IP
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.IP
     *
     * @param ip the value for STM_DEVICEINFO.IP
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.MAC
     *
     * @return the value of STM_DEVICEINFO.MAC
     *
     * @mbg.generated
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.MAC
     *
     * @param mac the value for STM_DEVICEINFO.MAC
     *
     * @mbg.generated
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.ADDRESS
     *
     * @return the value of STM_DEVICEINFO.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.ADDRESS
     *
     * @param address the value for STM_DEVICEINFO.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DEV_LONG
     *
     * @return the value of STM_DEVICEINFO.DEV_LONG
     *
     * @mbg.generated
     */
    public String getDevLong() {
        return devLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DEV_LONG
     *
     * @param devLong the value for STM_DEVICEINFO.DEV_LONG
     *
     * @mbg.generated
     */
    public void setDevLong(String devLong) {
        this.devLong = devLong == null ? null : devLong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DEV_LAT
     *
     * @return the value of STM_DEVICEINFO.DEV_LAT
     *
     * @mbg.generated
     */
    public String getDevLat() {
        return devLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DEV_LAT
     *
     * @param devLat the value for STM_DEVICEINFO.DEV_LAT
     *
     * @mbg.generated
     */
    public void setDevLat(String devLat) {
        this.devLat = devLat == null ? null : devLat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.MODEL
     *
     * @return the value of STM_DEVICEINFO.MODEL
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.MODEL
     *
     * @param model the value for STM_DEVICEINFO.MODEL
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.STOPDATE
     *
     * @return the value of STM_DEVICEINFO.STOPDATE
     *
     * @mbg.generated
     */
    public String getStopdate() {
        return stopdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.STOPDATE
     *
     * @param stopdate the value for STM_DEVICEINFO.STOPDATE
     *
     * @mbg.generated
     */
    public void setStopdate(String stopdate) {
        this.stopdate = stopdate == null ? null : stopdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.WARRANTYDATE
     *
     * @return the value of STM_DEVICEINFO.WARRANTYDATE
     *
     * @mbg.generated
     */
    public String getWarrantydate() {
        return warrantydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.WARRANTYDATE
     *
     * @param warrantydate the value for STM_DEVICEINFO.WARRANTYDATE
     *
     * @mbg.generated
     */
    public void setWarrantydate(String warrantydate) {
        this.warrantydate = warrantydate == null ? null : warrantydate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DEV_STATE
     *
     * @return the value of STM_DEVICEINFO.DEV_STATE
     *
     * @mbg.generated
     */
    public String getDevState() {
        return devState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DEV_STATE
     *
     * @param devState the value for STM_DEVICEINFO.DEV_STATE
     *
     * @mbg.generated
     */
    public void setDevState(String devState) {
        this.devState = devState == null ? null : devState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DISABLE_REASON
     *
     * @return the value of STM_DEVICEINFO.DISABLE_REASON
     *
     * @mbg.generated
     */
    public String getDisableReason() {
        return disableReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DISABLE_REASON
     *
     * @param disableReason the value for STM_DEVICEINFO.DISABLE_REASON
     *
     * @mbg.generated
     */
    public void setDisableReason(String disableReason) {
        this.disableReason = disableReason == null ? null : disableReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.MAINTENANCEMAN
     *
     * @return the value of STM_DEVICEINFO.MAINTENANCEMAN
     *
     * @mbg.generated
     */
    public String getMaintenanceman() {
        return maintenanceman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.MAINTENANCEMAN
     *
     * @param maintenanceman the value for STM_DEVICEINFO.MAINTENANCEMAN
     *
     * @mbg.generated
     */
    public void setMaintenanceman(String maintenanceman) {
        this.maintenanceman = maintenanceman == null ? null : maintenanceman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.MAINTENANCEPHONE
     *
     * @return the value of STM_DEVICEINFO.MAINTENANCEPHONE
     *
     * @mbg.generated
     */
    public String getMaintenancephone() {
        return maintenancephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.MAINTENANCEPHONE
     *
     * @param maintenancephone the value for STM_DEVICEINFO.MAINTENANCEPHONE
     *
     * @mbg.generated
     */
    public void setMaintenancephone(String maintenancephone) {
        this.maintenancephone = maintenancephone == null ? null : maintenancephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.MAINTENANCEPWD
     *
     * @return the value of STM_DEVICEINFO.MAINTENANCEPWD
     *
     * @mbg.generated
     */
    public String getMaintenancepwd() {
        return maintenancepwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.MAINTENANCEPWD
     *
     * @param maintenancepwd the value for STM_DEVICEINFO.MAINTENANCEPWD
     *
     * @mbg.generated
     */
    public void setMaintenancepwd(String maintenancepwd) {
        this.maintenancepwd = maintenancepwd == null ? null : maintenancepwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.PASSCODE
     *
     * @return the value of STM_DEVICEINFO.PASSCODE
     *
     * @mbg.generated
     */
    public Short getPasscode() {
        return passcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.PASSCODE
     *
     * @param passcode the value for STM_DEVICEINFO.PASSCODE
     *
     * @mbg.generated
     */
    public void setPasscode(Short passcode) {
        this.passcode = passcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.TELLERID
     *
     * @return the value of STM_DEVICEINFO.TELLERID
     *
     * @mbg.generated
     */
    public String getTellerid() {
        return tellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.TELLERID
     *
     * @param tellerid the value for STM_DEVICEINFO.TELLERID
     *
     * @mbg.generated
     */
    public void setTellerid(String tellerid) {
        this.tellerid = tellerid == null ? null : tellerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.TELLERNAME
     *
     * @return the value of STM_DEVICEINFO.TELLERNAME
     *
     * @mbg.generated
     */
    public String getTellername() {
        return tellername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.TELLERNAME
     *
     * @param tellername the value for STM_DEVICEINFO.TELLERNAME
     *
     * @mbg.generated
     */
    public void setTellername(String tellername) {
        this.tellername = tellername == null ? null : tellername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.LMK
     *
     * @return the value of STM_DEVICEINFO.LMK
     *
     * @mbg.generated
     */
    public String getLmk() {
        return lmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.LMK
     *
     * @param lmk the value for STM_DEVICEINFO.LMK
     *
     * @mbg.generated
     */
    public void setLmk(String lmk) {
        this.lmk = lmk == null ? null : lmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.REMARK1
     *
     * @return the value of STM_DEVICEINFO.REMARK1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.REMARK1
     *
     * @param remark1 the value for STM_DEVICEINFO.REMARK1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.TMK
     *
     * @return the value of STM_DEVICEINFO.TMK
     *
     * @mbg.generated
     */
    public String getTmk() {
        return tmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.TMK
     *
     * @param tmk the value for STM_DEVICEINFO.TMK
     *
     * @mbg.generated
     */
    public void setTmk(String tmk) {
        this.tmk = tmk == null ? null : tmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.PIK
     *
     * @return the value of STM_DEVICEINFO.PIK
     *
     * @mbg.generated
     */
    public String getPik() {
        return pik;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.PIK
     *
     * @param pik the value for STM_DEVICEINFO.PIK
     *
     * @mbg.generated
     */
    public void setPik(String pik) {
        this.pik = pik == null ? null : pik.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.MAK
     *
     * @return the value of STM_DEVICEINFO.MAK
     *
     * @mbg.generated
     */
    public String getMak() {
        return mak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.MAK
     *
     * @param mak the value for STM_DEVICEINFO.MAK
     *
     * @mbg.generated
     */
    public void setMak(String mak) {
        this.mak = mak == null ? null : mak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.TRADE_SESSION
     *
     * @return the value of STM_DEVICEINFO.TRADE_SESSION
     *
     * @mbg.generated
     */
    public String getTradeSession() {
        return tradeSession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.TRADE_SESSION
     *
     * @param tradeSession the value for STM_DEVICEINFO.TRADE_SESSION
     *
     * @mbg.generated
     */
    public void setTradeSession(String tradeSession) {
        this.tradeSession = tradeSession == null ? null : tradeSession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.IS_CLEANING
     *
     * @return the value of STM_DEVICEINFO.IS_CLEANING
     *
     * @mbg.generated
     */
    public String getIsCleaning() {
        return isCleaning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.IS_CLEANING
     *
     * @param isCleaning the value for STM_DEVICEINFO.IS_CLEANING
     *
     * @mbg.generated
     */
    public void setIsCleaning(String isCleaning) {
        this.isCleaning = isCleaning == null ? null : isCleaning.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.CASH_ERROR
     *
     * @return the value of STM_DEVICEINFO.CASH_ERROR
     *
     * @mbg.generated
     */
    public String getCashError() {
        return cashError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.CASH_ERROR
     *
     * @param cashError the value for STM_DEVICEINFO.CASH_ERROR
     *
     * @mbg.generated
     */
    public void setCashError(String cashError) {
        this.cashError = cashError == null ? null : cashError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DEVICE_TYPE
     *
     * @return the value of STM_DEVICEINFO.DEVICE_TYPE
     *
     * @mbg.generated
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DEVICE_TYPE
     *
     * @param deviceType the value for STM_DEVICEINFO.DEVICE_TYPE
     *
     * @mbg.generated
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.HSM_ID
     *
     * @return the value of STM_DEVICEINFO.HSM_ID
     *
     * @mbg.generated
     */
    public Short getHsmId() {
        return hsmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.HSM_ID
     *
     * @param hsmId the value for STM_DEVICEINFO.HSM_ID
     *
     * @mbg.generated
     */
    public void setHsmId(Short hsmId) {
        this.hsmId = hsmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.MASK
     *
     * @return the value of STM_DEVICEINFO.MASK
     *
     * @mbg.generated
     */
    public String getMask() {
        return mask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.MASK
     *
     * @param mask the value for STM_DEVICEINFO.MASK
     *
     * @mbg.generated
     */
    public void setMask(String mask) {
        this.mask = mask == null ? null : mask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.GATE_WAY
     *
     * @return the value of STM_DEVICEINFO.GATE_WAY
     *
     * @mbg.generated
     */
    public String getGateWay() {
        return gateWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.GATE_WAY
     *
     * @param gateWay the value for STM_DEVICEINFO.GATE_WAY
     *
     * @mbg.generated
     */
    public void setGateWay(String gateWay) {
        this.gateWay = gateWay == null ? null : gateWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DEV_OID
     *
     * @return the value of STM_DEVICEINFO.DEV_OID
     *
     * @mbg.generated
     */
    public String getDevOid() {
        return devOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DEV_OID
     *
     * @param devOid the value for STM_DEVICEINFO.DEV_OID
     *
     * @mbg.generated
     */
    public void setDevOid(String devOid) {
        this.devOid = devOid == null ? null : devOid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DEV_STATUS
     *
     * @return the value of STM_DEVICEINFO.DEV_STATUS
     *
     * @mbg.generated
     */
    public String getDevStatus() {
        return devStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DEV_STATUS
     *
     * @param devStatus the value for STM_DEVICEINFO.DEV_STATUS
     *
     * @mbg.generated
     */
    public void setDevStatus(String devStatus) {
        this.devStatus = devStatus == null ? null : devStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.CASH_ERROR_MSG
     *
     * @return the value of STM_DEVICEINFO.CASH_ERROR_MSG
     *
     * @mbg.generated
     */
    public String getCashErrorMsg() {
        return cashErrorMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.CASH_ERROR_MSG
     *
     * @param cashErrorMsg the value for STM_DEVICEINFO.CASH_ERROR_MSG
     *
     * @mbg.generated
     */
    public void setCashErrorMsg(String cashErrorMsg) {
        this.cashErrorMsg = cashErrorMsg == null ? null : cashErrorMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.LMK_TIME
     *
     * @return the value of STM_DEVICEINFO.LMK_TIME
     *
     * @mbg.generated
     */
    public String getLmkTime() {
        return lmkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.LMK_TIME
     *
     * @param lmkTime the value for STM_DEVICEINFO.LMK_TIME
     *
     * @mbg.generated
     */
    public void setLmkTime(String lmkTime) {
        this.lmkTime = lmkTime == null ? null : lmkTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.CASH_CYCLE
     *
     * @return the value of STM_DEVICEINFO.CASH_CYCLE
     *
     * @mbg.generated
     */
    public BigDecimal getCashCycle() {
        return cashCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.CASH_CYCLE
     *
     * @param cashCycle the value for STM_DEVICEINFO.CASH_CYCLE
     *
     * @mbg.generated
     */
    public void setCashCycle(BigDecimal cashCycle) {
        this.cashCycle = cashCycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.ONLINE_DATE
     *
     * @return the value of STM_DEVICEINFO.ONLINE_DATE
     *
     * @mbg.generated
     */
    public String getOnlineDate() {
        return onlineDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.ONLINE_DATE
     *
     * @param onlineDate the value for STM_DEVICEINFO.ONLINE_DATE
     *
     * @mbg.generated
     */
    public void setOnlineDate(String onlineDate) {
        this.onlineDate = onlineDate == null ? null : onlineDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.ONLINE_TIME
     *
     * @return the value of STM_DEVICEINFO.ONLINE_TIME
     *
     * @mbg.generated
     */
    public String getOnlineTime() {
        return onlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.ONLINE_TIME
     *
     * @param onlineTime the value for STM_DEVICEINFO.ONLINE_TIME
     *
     * @mbg.generated
     */
    public void setOnlineTime(String onlineTime) {
        this.onlineTime = onlineTime == null ? null : onlineTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.G_SYS_ID
     *
     * @return the value of STM_DEVICEINFO.G_SYS_ID
     *
     * @mbg.generated
     */
    public String getgSysId() {
        return gSysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.G_SYS_ID
     *
     * @param gSysId the value for STM_DEVICEINFO.G_SYS_ID
     *
     * @mbg.generated
     */
    public void setgSysId(String gSysId) {
        this.gSysId = gSysId == null ? null : gSysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.ZEROBILL_BOX
     *
     * @return the value of STM_DEVICEINFO.ZEROBILL_BOX
     *
     * @mbg.generated
     */
    public String getZerobillBox() {
        return zerobillBox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.ZEROBILL_BOX
     *
     * @param zerobillBox the value for STM_DEVICEINFO.ZEROBILL_BOX
     *
     * @mbg.generated
     */
    public void setZerobillBox(String zerobillBox) {
        this.zerobillBox = zerobillBox == null ? null : zerobillBox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.SOCIAL_NO
     *
     * @return the value of STM_DEVICEINFO.SOCIAL_NO
     *
     * @mbg.generated
     */
    public String getSocialNo() {
        return socialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.SOCIAL_NO
     *
     * @param socialNo the value for STM_DEVICEINFO.SOCIAL_NO
     *
     * @mbg.generated
     */
    public void setSocialNo(String socialNo) {
        this.socialNo = socialNo == null ? null : socialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.DEV_GRAY
     *
     * @return the value of STM_DEVICEINFO.DEV_GRAY
     *
     * @mbg.generated
     */
    public String getDevGray() {
        return devGray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.DEV_GRAY
     *
     * @param devGray the value for STM_DEVICEINFO.DEV_GRAY
     *
     * @mbg.generated
     */
    public void setDevGray(String devGray) {
        this.devGray = devGray == null ? null : devGray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.LOCKED
     *
     * @return the value of STM_DEVICEINFO.LOCKED
     *
     * @mbg.generated
     */
    public String getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.LOCKED
     *
     * @param locked the value for STM_DEVICEINFO.LOCKED
     *
     * @mbg.generated
     */
    public void setLocked(String locked) {
        this.locked = locked == null ? null : locked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.CASHBOX_DEPOSIT
     *
     * @return the value of STM_DEVICEINFO.CASHBOX_DEPOSIT
     *
     * @mbg.generated
     */
    public String getCashboxDeposit() {
        return cashboxDeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.CASHBOX_DEPOSIT
     *
     * @param cashboxDeposit the value for STM_DEVICEINFO.CASHBOX_DEPOSIT
     *
     * @mbg.generated
     */
    public void setCashboxDeposit(String cashboxDeposit) {
        this.cashboxDeposit = cashboxDeposit == null ? null : cashboxDeposit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.CASHBOX_WITHDRAWAL
     *
     * @return the value of STM_DEVICEINFO.CASHBOX_WITHDRAWAL
     *
     * @mbg.generated
     */
    public String getCashboxWithdrawal() {
        return cashboxWithdrawal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.CASHBOX_WITHDRAWAL
     *
     * @param cashboxWithdrawal the value for STM_DEVICEINFO.CASHBOX_WITHDRAWAL
     *
     * @mbg.generated
     */
    public void setCashboxWithdrawal(String cashboxWithdrawal) {
        this.cashboxWithdrawal = cashboxWithdrawal == null ? null : cashboxWithdrawal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.CASHBOX_OPTION
     *
     * @return the value of STM_DEVICEINFO.CASHBOX_OPTION
     *
     * @mbg.generated
     */
    public String getCashboxOption() {
        return cashboxOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.CASHBOX_OPTION
     *
     * @param cashboxOption the value for STM_DEVICEINFO.CASHBOX_OPTION
     *
     * @mbg.generated
     */
    public void setCashboxOption(String cashboxOption) {
        this.cashboxOption = cashboxOption == null ? null : cashboxOption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_DEVICEINFO.CASHBOX_CHANGE_BFADD
     *
     * @return the value of STM_DEVICEINFO.CASHBOX_CHANGE_BFADD
     *
     * @mbg.generated
     */
    public String getCashboxChangeBfadd() {
        return cashboxChangeBfadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_DEVICEINFO.CASHBOX_CHANGE_BFADD
     *
     * @param cashboxChangeBfadd the value for STM_DEVICEINFO.CASHBOX_CHANGE_BFADD
     *
     * @mbg.generated
     */
    public void setCashboxChangeBfadd(String cashboxChangeBfadd) {
        this.cashboxChangeBfadd = cashboxChangeBfadd == null ? null : cashboxChangeBfadd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orgid=").append(orgid);
        sb.append(", ip=").append(ip);
        sb.append(", mac=").append(mac);
        sb.append(", address=").append(address);
        sb.append(", devLong=").append(devLong);
        sb.append(", devLat=").append(devLat);
        sb.append(", model=").append(model);
        sb.append(", stopdate=").append(stopdate);
        sb.append(", warrantydate=").append(warrantydate);
        sb.append(", devState=").append(devState);
        sb.append(", disableReason=").append(disableReason);
        sb.append(", maintenanceman=").append(maintenanceman);
        sb.append(", maintenancephone=").append(maintenancephone);
        sb.append(", maintenancepwd=").append(maintenancepwd);
        sb.append(", passcode=").append(passcode);
        sb.append(", tellerid=").append(tellerid);
        sb.append(", tellername=").append(tellername);
        sb.append(", lmk=").append(lmk);
        sb.append(", remark1=").append(remark1);
        sb.append(", tmk=").append(tmk);
        sb.append(", pik=").append(pik);
        sb.append(", mak=").append(mak);
        sb.append(", tradeSession=").append(tradeSession);
        sb.append(", isCleaning=").append(isCleaning);
        sb.append(", cashError=").append(cashError);
        sb.append(", deviceType=").append(deviceType);
        sb.append(", hsmId=").append(hsmId);
        sb.append(", mask=").append(mask);
        sb.append(", gateWay=").append(gateWay);
        sb.append(", devOid=").append(devOid);
        sb.append(", devStatus=").append(devStatus);
        sb.append(", cashErrorMsg=").append(cashErrorMsg);
        sb.append(", lmkTime=").append(lmkTime);
        sb.append(", cashCycle=").append(cashCycle);
        sb.append(", onlineDate=").append(onlineDate);
        sb.append(", onlineTime=").append(onlineTime);
        sb.append(", gSysId=").append(gSysId);
        sb.append(", zerobillBox=").append(zerobillBox);
        sb.append(", socialNo=").append(socialNo);
        sb.append(", devGray=").append(devGray);
        sb.append(", locked=").append(locked);
        sb.append(", cashboxDeposit=").append(cashboxDeposit);
        sb.append(", cashboxWithdrawal=").append(cashboxWithdrawal);
        sb.append(", cashboxOption=").append(cashboxOption);
        sb.append(", cashboxChangeBfadd=").append(cashboxChangeBfadd);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}