package com.cpw.sqlview.sqlview.pojo;

import java.io.Serializable;
import java.math.BigDecimal;

public class StmFinInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CASH_FLAG
     *
     * @mbg.generated
     */
    private String cashFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CHANNELS
     *
     * @mbg.generated
     */
    private String channels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CLIENT_GROUPS
     *
     * @mbg.generated
     */
    private String clientGroups;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CLOSE_TIME
     *
     * @mbg.generated
     */
    private String closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CONTROL_FLAG
     *
     * @mbg.generated
     */
    private String controlFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CONTROL_FLAG2
     *
     * @mbg.generated
     */
    private String controlFlag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CONV_FLAG
     *
     * @mbg.generated
     */
    private String convFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CURR_TYPE
     *
     * @mbg.generated
     */
    private String currType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CYCLE_CFMDATE
     *
     * @mbg.generated
     */
    private String cycleCfmdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CYCLE_OPENEND
     *
     * @mbg.generated
     */
    private String cycleOpenend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CYCLE_OPENSTART
     *
     * @mbg.generated
     */
    private String cycleOpenstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.DIR_FREE_DATE
     *
     * @mbg.generated
     */
    private String dirFreeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.DIV_DAYS
     *
     * @mbg.generated
     */
    private String divDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.DIV_MODE
     *
     * @mbg.generated
     */
    private String divMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.DIV_MODES
     *
     * @mbg.generated
     */
    private String divModes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.END_DATE
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.ESTAB_DATE
     *
     * @mbg.generated
     */
    private String estabDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.FACE_VALUE
     *
     * @mbg.generated
     */
    private String faceValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.FAIL_DAYS
     *
     * @mbg.generated
     */
    private String failDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.GUEST_RATE
     *
     * @mbg.generated
     */
    private BigDecimal guestRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.INCOME_DATE
     *
     * @mbg.generated
     */
    private String incomeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.INCOME_ENDDATE
     *
     * @mbg.generated
     */
    private String incomeEnddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.INST_ALLOW
     *
     * @mbg.generated
     */
    private String instAllow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.INTEREST_DAYS
     *
     * @mbg.generated
     */
    private String interestDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.IPO_END_DATE
     *
     * @mbg.generated
     */
    private String ipoEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.IPO_START_DATE
     *
     * @mbg.generated
     */
    private String ipoStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.IS_CYCLE_PRD
     *
     * @mbg.generated
     */
    private String isCyclePrd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.IS_NEW_CUST
     *
     * @mbg.generated
     */
    private String isNewCust;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.ISS_PRICE
     *
     * @mbg.generated
     */
    private String issPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.LAST_DATE
     *
     * @mbg.generated
     */
    private String lastDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.MODEL_COMMENT
     *
     * @mbg.generated
     */
    private String modelComment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.NAV
     *
     * @mbg.generated
     */
    private String nav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.NEXT_CYCLE_CFMDATE
     *
     * @mbg.generated
     */
    private String nextCycleCfmdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.NEXT_CYCLE_ENDDATE
     *
     * @mbg.generated
     */
    private String nextCycleEnddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.NEXT_CYCLE_OPENEND
     *
     * @mbg.generated
     */
    private String nextCycleOpenend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.NEXT_CYCLE_OPENSTART
     *
     * @mbg.generated
     */
    private String nextCycleOpenstart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.NEXT_CYCLE_STARTDATE
     *
     * @mbg.generated
     */
    private String nextCycleStartdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.NEXT_DATE
     *
     * @mbg.generated
     */
    private String nextDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OAPP_AMT
     *
     * @mbg.generated
     */
    private String oappAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OFIRST_AMT
     *
     * @mbg.generated
     */
    private String ofirstAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OMAX_ACCAMT
     *
     * @mbg.generated
     */
    private String omaxAccamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OMAX_AMT
     *
     * @mbg.generated
     */
    private String omaxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OMAX_RED
     *
     * @mbg.generated
     */
    private String omaxRed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OMIN_CONVVOL
     *
     * @mbg.generated
     */
    private String ominConvvol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OMIN_HOLD
     *
     * @mbg.generated
     */
    private String ominHold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OMIN_INVEST_AMT
     *
     * @mbg.generated
     */
    private String ominInvestAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OMIN_RED
     *
     * @mbg.generated
     */
    private String ominRed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OPEN_TIME
     *
     * @mbg.generated
     */
    private String openTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OSUB_UNIT
     *
     * @mbg.generated
     */
    private String osubUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.OSURPLUS_LIMIT
     *
     * @mbg.generated
     */
    private String osurplusLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PAPP_AMT
     *
     * @mbg.generated
     */
    private String pappAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PER_ALLOW
     *
     * @mbg.generated
     */
    private String perAllow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PFIRST_AMT
     *
     * @mbg.generated
     */
    private BigDecimal pfirstAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PMAX_ACCAMT
     *
     * @mbg.generated
     */
    private String pmaxAccamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PMAX_AMT
     *
     * @mbg.generated
     */
    private String pmaxAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PMAX_RED
     *
     * @mbg.generated
     */
    private String pmaxRed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PMIN_CONVVOL
     *
     * @mbg.generated
     */
    private String pminConvvol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PMIN_HOLD
     *
     * @mbg.generated
     */
    private String pminHold;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PMIN_INVEST_AMT
     *
     * @mbg.generated
     */
    private String pminInvestAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PMIN_RED
     *
     * @mbg.generated
     */
    private String pminRed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_ATTR
     *
     * @mbg.generated
     */
    private String prdAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_CODE
     *
     * @mbg.generated
     */
    private String prdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_MANAGER
     *
     * @mbg.generated
     */
    private String prdManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_MAX_BALA
     *
     * @mbg.generated
     */
    private String prdMaxBala;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_MIN_BALA
     *
     * @mbg.generated
     */
    private String prdMinBala;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_NAME
     *
     * @mbg.generated
     */
    private String prdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_SCALE
     *
     * @mbg.generated
     */
    private String prdScale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_SPONSOR
     *
     * @mbg.generated
     */
    private String prdSponsor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_TEMPLATE
     *
     * @mbg.generated
     */
    private String prdTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_TRUSTEE
     *
     * @mbg.generated
     */
    private String prdTrustee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_TYPE
     *
     * @mbg.generated
     */
    private String prdType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PRD_TYPE_TJYH
     *
     * @mbg.generated
     */
    private String prdTypeTjyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PROTOCOL_NAME
     *
     * @mbg.generated
     */
    private String protocolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PSUB_UNIT
     *
     * @mbg.generated
     */
    private String psubUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.PSURPLUS_LIMIT
     *
     * @mbg.generated
     */
    private String psurplusLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.RED_DAYS
     *
     * @mbg.generated
     */
    private String redDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.REFUND_DAYS
     *
     * @mbg.generated
     */
    private String refundDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.RISK_LEVEL
     *
     * @mbg.generated
     */
    private String riskLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.RISK_NAME
     *
     * @mbg.generated
     */
    private String riskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.SALE_STATUS
     *
     * @mbg.generated
     */
    private String saleStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.SHARE_CLASS
     *
     * @mbg.generated
     */
    private String shareClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.STATUS_NAME
     *
     * @mbg.generated
     */
    private String statusName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.TACODE
     *
     * @mbg.generated
     */
    private String tacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.TOT_NAV
     *
     * @mbg.generated
     */
    private String totNav;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.TOT_VOL
     *
     * @mbg.generated
     */
    private String totVol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.TRANS_WAY
     *
     * @mbg.generated
     */
    private String transWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.TYPE_NAME
     *
     * @mbg.generated
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.TYPE_NO
     *
     * @mbg.generated
     */
    private String typeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.ASSIGNMENTFLAG
     *
     * @mbg.generated
     */
    private String assignmentflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.SUBLETTINGFLAG
     *
     * @mbg.generated
     */
    private String sublettingflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CYCLEDAY
     *
     * @mbg.generated
     */
    private String cycleday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.REDEEMFLAG
     *
     * @mbg.generated
     */
    private String redeemflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.JHONLYFLAG
     *
     * @mbg.generated
     */
    private String jhonlyflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.MODEL_COMMENT2
     *
     * @mbg.generated
     */
    private String modelComment2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_FIN_INFO.CYCYLESTATUS
     *
     * @mbg.generated
     */
    private String cycylestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CASH_FLAG
     *
     * @return the value of STM_FIN_INFO.CASH_FLAG
     *
     * @mbg.generated
     */
    public String getCashFlag() {
        return cashFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CASH_FLAG
     *
     * @param cashFlag the value for STM_FIN_INFO.CASH_FLAG
     *
     * @mbg.generated
     */
    public void setCashFlag(String cashFlag) {
        this.cashFlag = cashFlag == null ? null : cashFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CHANNELS
     *
     * @return the value of STM_FIN_INFO.CHANNELS
     *
     * @mbg.generated
     */
    public String getChannels() {
        return channels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CHANNELS
     *
     * @param channels the value for STM_FIN_INFO.CHANNELS
     *
     * @mbg.generated
     */
    public void setChannels(String channels) {
        this.channels = channels == null ? null : channels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CLIENT_GROUPS
     *
     * @return the value of STM_FIN_INFO.CLIENT_GROUPS
     *
     * @mbg.generated
     */
    public String getClientGroups() {
        return clientGroups;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CLIENT_GROUPS
     *
     * @param clientGroups the value for STM_FIN_INFO.CLIENT_GROUPS
     *
     * @mbg.generated
     */
    public void setClientGroups(String clientGroups) {
        this.clientGroups = clientGroups == null ? null : clientGroups.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CLOSE_TIME
     *
     * @return the value of STM_FIN_INFO.CLOSE_TIME
     *
     * @mbg.generated
     */
    public String getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CLOSE_TIME
     *
     * @param closeTime the value for STM_FIN_INFO.CLOSE_TIME
     *
     * @mbg.generated
     */
    public void setCloseTime(String closeTime) {
        this.closeTime = closeTime == null ? null : closeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CONTROL_FLAG
     *
     * @return the value of STM_FIN_INFO.CONTROL_FLAG
     *
     * @mbg.generated
     */
    public String getControlFlag() {
        return controlFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CONTROL_FLAG
     *
     * @param controlFlag the value for STM_FIN_INFO.CONTROL_FLAG
     *
     * @mbg.generated
     */
    public void setControlFlag(String controlFlag) {
        this.controlFlag = controlFlag == null ? null : controlFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CONTROL_FLAG2
     *
     * @return the value of STM_FIN_INFO.CONTROL_FLAG2
     *
     * @mbg.generated
     */
    public String getControlFlag2() {
        return controlFlag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CONTROL_FLAG2
     *
     * @param controlFlag2 the value for STM_FIN_INFO.CONTROL_FLAG2
     *
     * @mbg.generated
     */
    public void setControlFlag2(String controlFlag2) {
        this.controlFlag2 = controlFlag2 == null ? null : controlFlag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CONV_FLAG
     *
     * @return the value of STM_FIN_INFO.CONV_FLAG
     *
     * @mbg.generated
     */
    public String getConvFlag() {
        return convFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CONV_FLAG
     *
     * @param convFlag the value for STM_FIN_INFO.CONV_FLAG
     *
     * @mbg.generated
     */
    public void setConvFlag(String convFlag) {
        this.convFlag = convFlag == null ? null : convFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CURR_TYPE
     *
     * @return the value of STM_FIN_INFO.CURR_TYPE
     *
     * @mbg.generated
     */
    public String getCurrType() {
        return currType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CURR_TYPE
     *
     * @param currType the value for STM_FIN_INFO.CURR_TYPE
     *
     * @mbg.generated
     */
    public void setCurrType(String currType) {
        this.currType = currType == null ? null : currType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CYCLE_CFMDATE
     *
     * @return the value of STM_FIN_INFO.CYCLE_CFMDATE
     *
     * @mbg.generated
     */
    public String getCycleCfmdate() {
        return cycleCfmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CYCLE_CFMDATE
     *
     * @param cycleCfmdate the value for STM_FIN_INFO.CYCLE_CFMDATE
     *
     * @mbg.generated
     */
    public void setCycleCfmdate(String cycleCfmdate) {
        this.cycleCfmdate = cycleCfmdate == null ? null : cycleCfmdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CYCLE_OPENEND
     *
     * @return the value of STM_FIN_INFO.CYCLE_OPENEND
     *
     * @mbg.generated
     */
    public String getCycleOpenend() {
        return cycleOpenend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CYCLE_OPENEND
     *
     * @param cycleOpenend the value for STM_FIN_INFO.CYCLE_OPENEND
     *
     * @mbg.generated
     */
    public void setCycleOpenend(String cycleOpenend) {
        this.cycleOpenend = cycleOpenend == null ? null : cycleOpenend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CYCLE_OPENSTART
     *
     * @return the value of STM_FIN_INFO.CYCLE_OPENSTART
     *
     * @mbg.generated
     */
    public String getCycleOpenstart() {
        return cycleOpenstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CYCLE_OPENSTART
     *
     * @param cycleOpenstart the value for STM_FIN_INFO.CYCLE_OPENSTART
     *
     * @mbg.generated
     */
    public void setCycleOpenstart(String cycleOpenstart) {
        this.cycleOpenstart = cycleOpenstart == null ? null : cycleOpenstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.DIR_FREE_DATE
     *
     * @return the value of STM_FIN_INFO.DIR_FREE_DATE
     *
     * @mbg.generated
     */
    public String getDirFreeDate() {
        return dirFreeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.DIR_FREE_DATE
     *
     * @param dirFreeDate the value for STM_FIN_INFO.DIR_FREE_DATE
     *
     * @mbg.generated
     */
    public void setDirFreeDate(String dirFreeDate) {
        this.dirFreeDate = dirFreeDate == null ? null : dirFreeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.DIV_DAYS
     *
     * @return the value of STM_FIN_INFO.DIV_DAYS
     *
     * @mbg.generated
     */
    public String getDivDays() {
        return divDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.DIV_DAYS
     *
     * @param divDays the value for STM_FIN_INFO.DIV_DAYS
     *
     * @mbg.generated
     */
    public void setDivDays(String divDays) {
        this.divDays = divDays == null ? null : divDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.DIV_MODE
     *
     * @return the value of STM_FIN_INFO.DIV_MODE
     *
     * @mbg.generated
     */
    public String getDivMode() {
        return divMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.DIV_MODE
     *
     * @param divMode the value for STM_FIN_INFO.DIV_MODE
     *
     * @mbg.generated
     */
    public void setDivMode(String divMode) {
        this.divMode = divMode == null ? null : divMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.DIV_MODES
     *
     * @return the value of STM_FIN_INFO.DIV_MODES
     *
     * @mbg.generated
     */
    public String getDivModes() {
        return divModes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.DIV_MODES
     *
     * @param divModes the value for STM_FIN_INFO.DIV_MODES
     *
     * @mbg.generated
     */
    public void setDivModes(String divModes) {
        this.divModes = divModes == null ? null : divModes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.END_DATE
     *
     * @return the value of STM_FIN_INFO.END_DATE
     *
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.END_DATE
     *
     * @param endDate the value for STM_FIN_INFO.END_DATE
     *
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.ESTAB_DATE
     *
     * @return the value of STM_FIN_INFO.ESTAB_DATE
     *
     * @mbg.generated
     */
    public String getEstabDate() {
        return estabDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.ESTAB_DATE
     *
     * @param estabDate the value for STM_FIN_INFO.ESTAB_DATE
     *
     * @mbg.generated
     */
    public void setEstabDate(String estabDate) {
        this.estabDate = estabDate == null ? null : estabDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.FACE_VALUE
     *
     * @return the value of STM_FIN_INFO.FACE_VALUE
     *
     * @mbg.generated
     */
    public String getFaceValue() {
        return faceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.FACE_VALUE
     *
     * @param faceValue the value for STM_FIN_INFO.FACE_VALUE
     *
     * @mbg.generated
     */
    public void setFaceValue(String faceValue) {
        this.faceValue = faceValue == null ? null : faceValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.FAIL_DAYS
     *
     * @return the value of STM_FIN_INFO.FAIL_DAYS
     *
     * @mbg.generated
     */
    public String getFailDays() {
        return failDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.FAIL_DAYS
     *
     * @param failDays the value for STM_FIN_INFO.FAIL_DAYS
     *
     * @mbg.generated
     */
    public void setFailDays(String failDays) {
        this.failDays = failDays == null ? null : failDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.GUEST_RATE
     *
     * @return the value of STM_FIN_INFO.GUEST_RATE
     *
     * @mbg.generated
     */
    public BigDecimal getGuestRate() {
        return guestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.GUEST_RATE
     *
     * @param guestRate the value for STM_FIN_INFO.GUEST_RATE
     *
     * @mbg.generated
     */
    public void setGuestRate(BigDecimal guestRate) {
        this.guestRate = guestRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.INCOME_DATE
     *
     * @return the value of STM_FIN_INFO.INCOME_DATE
     *
     * @mbg.generated
     */
    public String getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.INCOME_DATE
     *
     * @param incomeDate the value for STM_FIN_INFO.INCOME_DATE
     *
     * @mbg.generated
     */
    public void setIncomeDate(String incomeDate) {
        this.incomeDate = incomeDate == null ? null : incomeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.INCOME_ENDDATE
     *
     * @return the value of STM_FIN_INFO.INCOME_ENDDATE
     *
     * @mbg.generated
     */
    public String getIncomeEnddate() {
        return incomeEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.INCOME_ENDDATE
     *
     * @param incomeEnddate the value for STM_FIN_INFO.INCOME_ENDDATE
     *
     * @mbg.generated
     */
    public void setIncomeEnddate(String incomeEnddate) {
        this.incomeEnddate = incomeEnddate == null ? null : incomeEnddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.INST_ALLOW
     *
     * @return the value of STM_FIN_INFO.INST_ALLOW
     *
     * @mbg.generated
     */
    public String getInstAllow() {
        return instAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.INST_ALLOW
     *
     * @param instAllow the value for STM_FIN_INFO.INST_ALLOW
     *
     * @mbg.generated
     */
    public void setInstAllow(String instAllow) {
        this.instAllow = instAllow == null ? null : instAllow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.INTEREST_DAYS
     *
     * @return the value of STM_FIN_INFO.INTEREST_DAYS
     *
     * @mbg.generated
     */
    public String getInterestDays() {
        return interestDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.INTEREST_DAYS
     *
     * @param interestDays the value for STM_FIN_INFO.INTEREST_DAYS
     *
     * @mbg.generated
     */
    public void setInterestDays(String interestDays) {
        this.interestDays = interestDays == null ? null : interestDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.IPO_END_DATE
     *
     * @return the value of STM_FIN_INFO.IPO_END_DATE
     *
     * @mbg.generated
     */
    public String getIpoEndDate() {
        return ipoEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.IPO_END_DATE
     *
     * @param ipoEndDate the value for STM_FIN_INFO.IPO_END_DATE
     *
     * @mbg.generated
     */
    public void setIpoEndDate(String ipoEndDate) {
        this.ipoEndDate = ipoEndDate == null ? null : ipoEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.IPO_START_DATE
     *
     * @return the value of STM_FIN_INFO.IPO_START_DATE
     *
     * @mbg.generated
     */
    public String getIpoStartDate() {
        return ipoStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.IPO_START_DATE
     *
     * @param ipoStartDate the value for STM_FIN_INFO.IPO_START_DATE
     *
     * @mbg.generated
     */
    public void setIpoStartDate(String ipoStartDate) {
        this.ipoStartDate = ipoStartDate == null ? null : ipoStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.IS_CYCLE_PRD
     *
     * @return the value of STM_FIN_INFO.IS_CYCLE_PRD
     *
     * @mbg.generated
     */
    public String getIsCyclePrd() {
        return isCyclePrd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.IS_CYCLE_PRD
     *
     * @param isCyclePrd the value for STM_FIN_INFO.IS_CYCLE_PRD
     *
     * @mbg.generated
     */
    public void setIsCyclePrd(String isCyclePrd) {
        this.isCyclePrd = isCyclePrd == null ? null : isCyclePrd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.IS_NEW_CUST
     *
     * @return the value of STM_FIN_INFO.IS_NEW_CUST
     *
     * @mbg.generated
     */
    public String getIsNewCust() {
        return isNewCust;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.IS_NEW_CUST
     *
     * @param isNewCust the value for STM_FIN_INFO.IS_NEW_CUST
     *
     * @mbg.generated
     */
    public void setIsNewCust(String isNewCust) {
        this.isNewCust = isNewCust == null ? null : isNewCust.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.ISS_PRICE
     *
     * @return the value of STM_FIN_INFO.ISS_PRICE
     *
     * @mbg.generated
     */
    public String getIssPrice() {
        return issPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.ISS_PRICE
     *
     * @param issPrice the value for STM_FIN_INFO.ISS_PRICE
     *
     * @mbg.generated
     */
    public void setIssPrice(String issPrice) {
        this.issPrice = issPrice == null ? null : issPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.LAST_DATE
     *
     * @return the value of STM_FIN_INFO.LAST_DATE
     *
     * @mbg.generated
     */
    public String getLastDate() {
        return lastDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.LAST_DATE
     *
     * @param lastDate the value for STM_FIN_INFO.LAST_DATE
     *
     * @mbg.generated
     */
    public void setLastDate(String lastDate) {
        this.lastDate = lastDate == null ? null : lastDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.MODEL_COMMENT
     *
     * @return the value of STM_FIN_INFO.MODEL_COMMENT
     *
     * @mbg.generated
     */
    public String getModelComment() {
        return modelComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.MODEL_COMMENT
     *
     * @param modelComment the value for STM_FIN_INFO.MODEL_COMMENT
     *
     * @mbg.generated
     */
    public void setModelComment(String modelComment) {
        this.modelComment = modelComment == null ? null : modelComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.NAV
     *
     * @return the value of STM_FIN_INFO.NAV
     *
     * @mbg.generated
     */
    public String getNav() {
        return nav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.NAV
     *
     * @param nav the value for STM_FIN_INFO.NAV
     *
     * @mbg.generated
     */
    public void setNav(String nav) {
        this.nav = nav == null ? null : nav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.NEXT_CYCLE_CFMDATE
     *
     * @return the value of STM_FIN_INFO.NEXT_CYCLE_CFMDATE
     *
     * @mbg.generated
     */
    public String getNextCycleCfmdate() {
        return nextCycleCfmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.NEXT_CYCLE_CFMDATE
     *
     * @param nextCycleCfmdate the value for STM_FIN_INFO.NEXT_CYCLE_CFMDATE
     *
     * @mbg.generated
     */
    public void setNextCycleCfmdate(String nextCycleCfmdate) {
        this.nextCycleCfmdate = nextCycleCfmdate == null ? null : nextCycleCfmdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.NEXT_CYCLE_ENDDATE
     *
     * @return the value of STM_FIN_INFO.NEXT_CYCLE_ENDDATE
     *
     * @mbg.generated
     */
    public String getNextCycleEnddate() {
        return nextCycleEnddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.NEXT_CYCLE_ENDDATE
     *
     * @param nextCycleEnddate the value for STM_FIN_INFO.NEXT_CYCLE_ENDDATE
     *
     * @mbg.generated
     */
    public void setNextCycleEnddate(String nextCycleEnddate) {
        this.nextCycleEnddate = nextCycleEnddate == null ? null : nextCycleEnddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.NEXT_CYCLE_OPENEND
     *
     * @return the value of STM_FIN_INFO.NEXT_CYCLE_OPENEND
     *
     * @mbg.generated
     */
    public String getNextCycleOpenend() {
        return nextCycleOpenend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.NEXT_CYCLE_OPENEND
     *
     * @param nextCycleOpenend the value for STM_FIN_INFO.NEXT_CYCLE_OPENEND
     *
     * @mbg.generated
     */
    public void setNextCycleOpenend(String nextCycleOpenend) {
        this.nextCycleOpenend = nextCycleOpenend == null ? null : nextCycleOpenend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.NEXT_CYCLE_OPENSTART
     *
     * @return the value of STM_FIN_INFO.NEXT_CYCLE_OPENSTART
     *
     * @mbg.generated
     */
    public String getNextCycleOpenstart() {
        return nextCycleOpenstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.NEXT_CYCLE_OPENSTART
     *
     * @param nextCycleOpenstart the value for STM_FIN_INFO.NEXT_CYCLE_OPENSTART
     *
     * @mbg.generated
     */
    public void setNextCycleOpenstart(String nextCycleOpenstart) {
        this.nextCycleOpenstart = nextCycleOpenstart == null ? null : nextCycleOpenstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.NEXT_CYCLE_STARTDATE
     *
     * @return the value of STM_FIN_INFO.NEXT_CYCLE_STARTDATE
     *
     * @mbg.generated
     */
    public String getNextCycleStartdate() {
        return nextCycleStartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.NEXT_CYCLE_STARTDATE
     *
     * @param nextCycleStartdate the value for STM_FIN_INFO.NEXT_CYCLE_STARTDATE
     *
     * @mbg.generated
     */
    public void setNextCycleStartdate(String nextCycleStartdate) {
        this.nextCycleStartdate = nextCycleStartdate == null ? null : nextCycleStartdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.NEXT_DATE
     *
     * @return the value of STM_FIN_INFO.NEXT_DATE
     *
     * @mbg.generated
     */
    public String getNextDate() {
        return nextDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.NEXT_DATE
     *
     * @param nextDate the value for STM_FIN_INFO.NEXT_DATE
     *
     * @mbg.generated
     */
    public void setNextDate(String nextDate) {
        this.nextDate = nextDate == null ? null : nextDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OAPP_AMT
     *
     * @return the value of STM_FIN_INFO.OAPP_AMT
     *
     * @mbg.generated
     */
    public String getOappAmt() {
        return oappAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OAPP_AMT
     *
     * @param oappAmt the value for STM_FIN_INFO.OAPP_AMT
     *
     * @mbg.generated
     */
    public void setOappAmt(String oappAmt) {
        this.oappAmt = oappAmt == null ? null : oappAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OFIRST_AMT
     *
     * @return the value of STM_FIN_INFO.OFIRST_AMT
     *
     * @mbg.generated
     */
    public String getOfirstAmt() {
        return ofirstAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OFIRST_AMT
     *
     * @param ofirstAmt the value for STM_FIN_INFO.OFIRST_AMT
     *
     * @mbg.generated
     */
    public void setOfirstAmt(String ofirstAmt) {
        this.ofirstAmt = ofirstAmt == null ? null : ofirstAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OMAX_ACCAMT
     *
     * @return the value of STM_FIN_INFO.OMAX_ACCAMT
     *
     * @mbg.generated
     */
    public String getOmaxAccamt() {
        return omaxAccamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OMAX_ACCAMT
     *
     * @param omaxAccamt the value for STM_FIN_INFO.OMAX_ACCAMT
     *
     * @mbg.generated
     */
    public void setOmaxAccamt(String omaxAccamt) {
        this.omaxAccamt = omaxAccamt == null ? null : omaxAccamt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OMAX_AMT
     *
     * @return the value of STM_FIN_INFO.OMAX_AMT
     *
     * @mbg.generated
     */
    public String getOmaxAmt() {
        return omaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OMAX_AMT
     *
     * @param omaxAmt the value for STM_FIN_INFO.OMAX_AMT
     *
     * @mbg.generated
     */
    public void setOmaxAmt(String omaxAmt) {
        this.omaxAmt = omaxAmt == null ? null : omaxAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OMAX_RED
     *
     * @return the value of STM_FIN_INFO.OMAX_RED
     *
     * @mbg.generated
     */
    public String getOmaxRed() {
        return omaxRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OMAX_RED
     *
     * @param omaxRed the value for STM_FIN_INFO.OMAX_RED
     *
     * @mbg.generated
     */
    public void setOmaxRed(String omaxRed) {
        this.omaxRed = omaxRed == null ? null : omaxRed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OMIN_CONVVOL
     *
     * @return the value of STM_FIN_INFO.OMIN_CONVVOL
     *
     * @mbg.generated
     */
    public String getOminConvvol() {
        return ominConvvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OMIN_CONVVOL
     *
     * @param ominConvvol the value for STM_FIN_INFO.OMIN_CONVVOL
     *
     * @mbg.generated
     */
    public void setOminConvvol(String ominConvvol) {
        this.ominConvvol = ominConvvol == null ? null : ominConvvol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OMIN_HOLD
     *
     * @return the value of STM_FIN_INFO.OMIN_HOLD
     *
     * @mbg.generated
     */
    public String getOminHold() {
        return ominHold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OMIN_HOLD
     *
     * @param ominHold the value for STM_FIN_INFO.OMIN_HOLD
     *
     * @mbg.generated
     */
    public void setOminHold(String ominHold) {
        this.ominHold = ominHold == null ? null : ominHold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OMIN_INVEST_AMT
     *
     * @return the value of STM_FIN_INFO.OMIN_INVEST_AMT
     *
     * @mbg.generated
     */
    public String getOminInvestAmt() {
        return ominInvestAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OMIN_INVEST_AMT
     *
     * @param ominInvestAmt the value for STM_FIN_INFO.OMIN_INVEST_AMT
     *
     * @mbg.generated
     */
    public void setOminInvestAmt(String ominInvestAmt) {
        this.ominInvestAmt = ominInvestAmt == null ? null : ominInvestAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OMIN_RED
     *
     * @return the value of STM_FIN_INFO.OMIN_RED
     *
     * @mbg.generated
     */
    public String getOminRed() {
        return ominRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OMIN_RED
     *
     * @param ominRed the value for STM_FIN_INFO.OMIN_RED
     *
     * @mbg.generated
     */
    public void setOminRed(String ominRed) {
        this.ominRed = ominRed == null ? null : ominRed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OPEN_TIME
     *
     * @return the value of STM_FIN_INFO.OPEN_TIME
     *
     * @mbg.generated
     */
    public String getOpenTime() {
        return openTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OPEN_TIME
     *
     * @param openTime the value for STM_FIN_INFO.OPEN_TIME
     *
     * @mbg.generated
     */
    public void setOpenTime(String openTime) {
        this.openTime = openTime == null ? null : openTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OSUB_UNIT
     *
     * @return the value of STM_FIN_INFO.OSUB_UNIT
     *
     * @mbg.generated
     */
    public String getOsubUnit() {
        return osubUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OSUB_UNIT
     *
     * @param osubUnit the value for STM_FIN_INFO.OSUB_UNIT
     *
     * @mbg.generated
     */
    public void setOsubUnit(String osubUnit) {
        this.osubUnit = osubUnit == null ? null : osubUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.OSURPLUS_LIMIT
     *
     * @return the value of STM_FIN_INFO.OSURPLUS_LIMIT
     *
     * @mbg.generated
     */
    public String getOsurplusLimit() {
        return osurplusLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.OSURPLUS_LIMIT
     *
     * @param osurplusLimit the value for STM_FIN_INFO.OSURPLUS_LIMIT
     *
     * @mbg.generated
     */
    public void setOsurplusLimit(String osurplusLimit) {
        this.osurplusLimit = osurplusLimit == null ? null : osurplusLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PAPP_AMT
     *
     * @return the value of STM_FIN_INFO.PAPP_AMT
     *
     * @mbg.generated
     */
    public String getPappAmt() {
        return pappAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PAPP_AMT
     *
     * @param pappAmt the value for STM_FIN_INFO.PAPP_AMT
     *
     * @mbg.generated
     */
    public void setPappAmt(String pappAmt) {
        this.pappAmt = pappAmt == null ? null : pappAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PER_ALLOW
     *
     * @return the value of STM_FIN_INFO.PER_ALLOW
     *
     * @mbg.generated
     */
    public String getPerAllow() {
        return perAllow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PER_ALLOW
     *
     * @param perAllow the value for STM_FIN_INFO.PER_ALLOW
     *
     * @mbg.generated
     */
    public void setPerAllow(String perAllow) {
        this.perAllow = perAllow == null ? null : perAllow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PFIRST_AMT
     *
     * @return the value of STM_FIN_INFO.PFIRST_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getPfirstAmt() {
        return pfirstAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PFIRST_AMT
     *
     * @param pfirstAmt the value for STM_FIN_INFO.PFIRST_AMT
     *
     * @mbg.generated
     */
    public void setPfirstAmt(BigDecimal pfirstAmt) {
        this.pfirstAmt = pfirstAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PMAX_ACCAMT
     *
     * @return the value of STM_FIN_INFO.PMAX_ACCAMT
     *
     * @mbg.generated
     */
    public String getPmaxAccamt() {
        return pmaxAccamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PMAX_ACCAMT
     *
     * @param pmaxAccamt the value for STM_FIN_INFO.PMAX_ACCAMT
     *
     * @mbg.generated
     */
    public void setPmaxAccamt(String pmaxAccamt) {
        this.pmaxAccamt = pmaxAccamt == null ? null : pmaxAccamt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PMAX_AMT
     *
     * @return the value of STM_FIN_INFO.PMAX_AMT
     *
     * @mbg.generated
     */
    public String getPmaxAmt() {
        return pmaxAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PMAX_AMT
     *
     * @param pmaxAmt the value for STM_FIN_INFO.PMAX_AMT
     *
     * @mbg.generated
     */
    public void setPmaxAmt(String pmaxAmt) {
        this.pmaxAmt = pmaxAmt == null ? null : pmaxAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PMAX_RED
     *
     * @return the value of STM_FIN_INFO.PMAX_RED
     *
     * @mbg.generated
     */
    public String getPmaxRed() {
        return pmaxRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PMAX_RED
     *
     * @param pmaxRed the value for STM_FIN_INFO.PMAX_RED
     *
     * @mbg.generated
     */
    public void setPmaxRed(String pmaxRed) {
        this.pmaxRed = pmaxRed == null ? null : pmaxRed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PMIN_CONVVOL
     *
     * @return the value of STM_FIN_INFO.PMIN_CONVVOL
     *
     * @mbg.generated
     */
    public String getPminConvvol() {
        return pminConvvol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PMIN_CONVVOL
     *
     * @param pminConvvol the value for STM_FIN_INFO.PMIN_CONVVOL
     *
     * @mbg.generated
     */
    public void setPminConvvol(String pminConvvol) {
        this.pminConvvol = pminConvvol == null ? null : pminConvvol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PMIN_HOLD
     *
     * @return the value of STM_FIN_INFO.PMIN_HOLD
     *
     * @mbg.generated
     */
    public String getPminHold() {
        return pminHold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PMIN_HOLD
     *
     * @param pminHold the value for STM_FIN_INFO.PMIN_HOLD
     *
     * @mbg.generated
     */
    public void setPminHold(String pminHold) {
        this.pminHold = pminHold == null ? null : pminHold.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PMIN_INVEST_AMT
     *
     * @return the value of STM_FIN_INFO.PMIN_INVEST_AMT
     *
     * @mbg.generated
     */
    public String getPminInvestAmt() {
        return pminInvestAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PMIN_INVEST_AMT
     *
     * @param pminInvestAmt the value for STM_FIN_INFO.PMIN_INVEST_AMT
     *
     * @mbg.generated
     */
    public void setPminInvestAmt(String pminInvestAmt) {
        this.pminInvestAmt = pminInvestAmt == null ? null : pminInvestAmt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PMIN_RED
     *
     * @return the value of STM_FIN_INFO.PMIN_RED
     *
     * @mbg.generated
     */
    public String getPminRed() {
        return pminRed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PMIN_RED
     *
     * @param pminRed the value for STM_FIN_INFO.PMIN_RED
     *
     * @mbg.generated
     */
    public void setPminRed(String pminRed) {
        this.pminRed = pminRed == null ? null : pminRed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_ATTR
     *
     * @return the value of STM_FIN_INFO.PRD_ATTR
     *
     * @mbg.generated
     */
    public String getPrdAttr() {
        return prdAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_ATTR
     *
     * @param prdAttr the value for STM_FIN_INFO.PRD_ATTR
     *
     * @mbg.generated
     */
    public void setPrdAttr(String prdAttr) {
        this.prdAttr = prdAttr == null ? null : prdAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_CODE
     *
     * @return the value of STM_FIN_INFO.PRD_CODE
     *
     * @mbg.generated
     */
    public String getPrdCode() {
        return prdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_CODE
     *
     * @param prdCode the value for STM_FIN_INFO.PRD_CODE
     *
     * @mbg.generated
     */
    public void setPrdCode(String prdCode) {
        this.prdCode = prdCode == null ? null : prdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_MANAGER
     *
     * @return the value of STM_FIN_INFO.PRD_MANAGER
     *
     * @mbg.generated
     */
    public String getPrdManager() {
        return prdManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_MANAGER
     *
     * @param prdManager the value for STM_FIN_INFO.PRD_MANAGER
     *
     * @mbg.generated
     */
    public void setPrdManager(String prdManager) {
        this.prdManager = prdManager == null ? null : prdManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_MAX_BALA
     *
     * @return the value of STM_FIN_INFO.PRD_MAX_BALA
     *
     * @mbg.generated
     */
    public String getPrdMaxBala() {
        return prdMaxBala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_MAX_BALA
     *
     * @param prdMaxBala the value for STM_FIN_INFO.PRD_MAX_BALA
     *
     * @mbg.generated
     */
    public void setPrdMaxBala(String prdMaxBala) {
        this.prdMaxBala = prdMaxBala == null ? null : prdMaxBala.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_MIN_BALA
     *
     * @return the value of STM_FIN_INFO.PRD_MIN_BALA
     *
     * @mbg.generated
     */
    public String getPrdMinBala() {
        return prdMinBala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_MIN_BALA
     *
     * @param prdMinBala the value for STM_FIN_INFO.PRD_MIN_BALA
     *
     * @mbg.generated
     */
    public void setPrdMinBala(String prdMinBala) {
        this.prdMinBala = prdMinBala == null ? null : prdMinBala.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_NAME
     *
     * @return the value of STM_FIN_INFO.PRD_NAME
     *
     * @mbg.generated
     */
    public String getPrdName() {
        return prdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_NAME
     *
     * @param prdName the value for STM_FIN_INFO.PRD_NAME
     *
     * @mbg.generated
     */
    public void setPrdName(String prdName) {
        this.prdName = prdName == null ? null : prdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_SCALE
     *
     * @return the value of STM_FIN_INFO.PRD_SCALE
     *
     * @mbg.generated
     */
    public String getPrdScale() {
        return prdScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_SCALE
     *
     * @param prdScale the value for STM_FIN_INFO.PRD_SCALE
     *
     * @mbg.generated
     */
    public void setPrdScale(String prdScale) {
        this.prdScale = prdScale == null ? null : prdScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_SPONSOR
     *
     * @return the value of STM_FIN_INFO.PRD_SPONSOR
     *
     * @mbg.generated
     */
    public String getPrdSponsor() {
        return prdSponsor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_SPONSOR
     *
     * @param prdSponsor the value for STM_FIN_INFO.PRD_SPONSOR
     *
     * @mbg.generated
     */
    public void setPrdSponsor(String prdSponsor) {
        this.prdSponsor = prdSponsor == null ? null : prdSponsor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_TEMPLATE
     *
     * @return the value of STM_FIN_INFO.PRD_TEMPLATE
     *
     * @mbg.generated
     */
    public String getPrdTemplate() {
        return prdTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_TEMPLATE
     *
     * @param prdTemplate the value for STM_FIN_INFO.PRD_TEMPLATE
     *
     * @mbg.generated
     */
    public void setPrdTemplate(String prdTemplate) {
        this.prdTemplate = prdTemplate == null ? null : prdTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_TRUSTEE
     *
     * @return the value of STM_FIN_INFO.PRD_TRUSTEE
     *
     * @mbg.generated
     */
    public String getPrdTrustee() {
        return prdTrustee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_TRUSTEE
     *
     * @param prdTrustee the value for STM_FIN_INFO.PRD_TRUSTEE
     *
     * @mbg.generated
     */
    public void setPrdTrustee(String prdTrustee) {
        this.prdTrustee = prdTrustee == null ? null : prdTrustee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_TYPE
     *
     * @return the value of STM_FIN_INFO.PRD_TYPE
     *
     * @mbg.generated
     */
    public String getPrdType() {
        return prdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_TYPE
     *
     * @param prdType the value for STM_FIN_INFO.PRD_TYPE
     *
     * @mbg.generated
     */
    public void setPrdType(String prdType) {
        this.prdType = prdType == null ? null : prdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PRD_TYPE_TJYH
     *
     * @return the value of STM_FIN_INFO.PRD_TYPE_TJYH
     *
     * @mbg.generated
     */
    public String getPrdTypeTjyh() {
        return prdTypeTjyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PRD_TYPE_TJYH
     *
     * @param prdTypeTjyh the value for STM_FIN_INFO.PRD_TYPE_TJYH
     *
     * @mbg.generated
     */
    public void setPrdTypeTjyh(String prdTypeTjyh) {
        this.prdTypeTjyh = prdTypeTjyh == null ? null : prdTypeTjyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PROTOCOL_NAME
     *
     * @return the value of STM_FIN_INFO.PROTOCOL_NAME
     *
     * @mbg.generated
     */
    public String getProtocolName() {
        return protocolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PROTOCOL_NAME
     *
     * @param protocolName the value for STM_FIN_INFO.PROTOCOL_NAME
     *
     * @mbg.generated
     */
    public void setProtocolName(String protocolName) {
        this.protocolName = protocolName == null ? null : protocolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PSUB_UNIT
     *
     * @return the value of STM_FIN_INFO.PSUB_UNIT
     *
     * @mbg.generated
     */
    public String getPsubUnit() {
        return psubUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PSUB_UNIT
     *
     * @param psubUnit the value for STM_FIN_INFO.PSUB_UNIT
     *
     * @mbg.generated
     */
    public void setPsubUnit(String psubUnit) {
        this.psubUnit = psubUnit == null ? null : psubUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.PSURPLUS_LIMIT
     *
     * @return the value of STM_FIN_INFO.PSURPLUS_LIMIT
     *
     * @mbg.generated
     */
    public String getPsurplusLimit() {
        return psurplusLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.PSURPLUS_LIMIT
     *
     * @param psurplusLimit the value for STM_FIN_INFO.PSURPLUS_LIMIT
     *
     * @mbg.generated
     */
    public void setPsurplusLimit(String psurplusLimit) {
        this.psurplusLimit = psurplusLimit == null ? null : psurplusLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.RED_DAYS
     *
     * @return the value of STM_FIN_INFO.RED_DAYS
     *
     * @mbg.generated
     */
    public String getRedDays() {
        return redDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.RED_DAYS
     *
     * @param redDays the value for STM_FIN_INFO.RED_DAYS
     *
     * @mbg.generated
     */
    public void setRedDays(String redDays) {
        this.redDays = redDays == null ? null : redDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.REFUND_DAYS
     *
     * @return the value of STM_FIN_INFO.REFUND_DAYS
     *
     * @mbg.generated
     */
    public String getRefundDays() {
        return refundDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.REFUND_DAYS
     *
     * @param refundDays the value for STM_FIN_INFO.REFUND_DAYS
     *
     * @mbg.generated
     */
    public void setRefundDays(String refundDays) {
        this.refundDays = refundDays == null ? null : refundDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.RISK_LEVEL
     *
     * @return the value of STM_FIN_INFO.RISK_LEVEL
     *
     * @mbg.generated
     */
    public String getRiskLevel() {
        return riskLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.RISK_LEVEL
     *
     * @param riskLevel the value for STM_FIN_INFO.RISK_LEVEL
     *
     * @mbg.generated
     */
    public void setRiskLevel(String riskLevel) {
        this.riskLevel = riskLevel == null ? null : riskLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.RISK_NAME
     *
     * @return the value of STM_FIN_INFO.RISK_NAME
     *
     * @mbg.generated
     */
    public String getRiskName() {
        return riskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.RISK_NAME
     *
     * @param riskName the value for STM_FIN_INFO.RISK_NAME
     *
     * @mbg.generated
     */
    public void setRiskName(String riskName) {
        this.riskName = riskName == null ? null : riskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.SALE_STATUS
     *
     * @return the value of STM_FIN_INFO.SALE_STATUS
     *
     * @mbg.generated
     */
    public String getSaleStatus() {
        return saleStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.SALE_STATUS
     *
     * @param saleStatus the value for STM_FIN_INFO.SALE_STATUS
     *
     * @mbg.generated
     */
    public void setSaleStatus(String saleStatus) {
        this.saleStatus = saleStatus == null ? null : saleStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.SHARE_CLASS
     *
     * @return the value of STM_FIN_INFO.SHARE_CLASS
     *
     * @mbg.generated
     */
    public String getShareClass() {
        return shareClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.SHARE_CLASS
     *
     * @param shareClass the value for STM_FIN_INFO.SHARE_CLASS
     *
     * @mbg.generated
     */
    public void setShareClass(String shareClass) {
        this.shareClass = shareClass == null ? null : shareClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.STATUS
     *
     * @return the value of STM_FIN_INFO.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.STATUS
     *
     * @param status the value for STM_FIN_INFO.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.STATUS_NAME
     *
     * @return the value of STM_FIN_INFO.STATUS_NAME
     *
     * @mbg.generated
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.STATUS_NAME
     *
     * @param statusName the value for STM_FIN_INFO.STATUS_NAME
     *
     * @mbg.generated
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName == null ? null : statusName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.TACODE
     *
     * @return the value of STM_FIN_INFO.TACODE
     *
     * @mbg.generated
     */
    public String getTacode() {
        return tacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.TACODE
     *
     * @param tacode the value for STM_FIN_INFO.TACODE
     *
     * @mbg.generated
     */
    public void setTacode(String tacode) {
        this.tacode = tacode == null ? null : tacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.TOT_NAV
     *
     * @return the value of STM_FIN_INFO.TOT_NAV
     *
     * @mbg.generated
     */
    public String getTotNav() {
        return totNav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.TOT_NAV
     *
     * @param totNav the value for STM_FIN_INFO.TOT_NAV
     *
     * @mbg.generated
     */
    public void setTotNav(String totNav) {
        this.totNav = totNav == null ? null : totNav.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.TOT_VOL
     *
     * @return the value of STM_FIN_INFO.TOT_VOL
     *
     * @mbg.generated
     */
    public String getTotVol() {
        return totVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.TOT_VOL
     *
     * @param totVol the value for STM_FIN_INFO.TOT_VOL
     *
     * @mbg.generated
     */
    public void setTotVol(String totVol) {
        this.totVol = totVol == null ? null : totVol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.TRANS_WAY
     *
     * @return the value of STM_FIN_INFO.TRANS_WAY
     *
     * @mbg.generated
     */
    public String getTransWay() {
        return transWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.TRANS_WAY
     *
     * @param transWay the value for STM_FIN_INFO.TRANS_WAY
     *
     * @mbg.generated
     */
    public void setTransWay(String transWay) {
        this.transWay = transWay == null ? null : transWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.TYPE_NAME
     *
     * @return the value of STM_FIN_INFO.TYPE_NAME
     *
     * @mbg.generated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.TYPE_NAME
     *
     * @param typeName the value for STM_FIN_INFO.TYPE_NAME
     *
     * @mbg.generated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.TYPE_NO
     *
     * @return the value of STM_FIN_INFO.TYPE_NO
     *
     * @mbg.generated
     */
    public String getTypeNo() {
        return typeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.TYPE_NO
     *
     * @param typeNo the value for STM_FIN_INFO.TYPE_NO
     *
     * @mbg.generated
     */
    public void setTypeNo(String typeNo) {
        this.typeNo = typeNo == null ? null : typeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.UPDATE_TIME
     *
     * @return the value of STM_FIN_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.UPDATE_TIME
     *
     * @param updateTime the value for STM_FIN_INFO.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.ASSIGNMENTFLAG
     *
     * @return the value of STM_FIN_INFO.ASSIGNMENTFLAG
     *
     * @mbg.generated
     */
    public String getAssignmentflag() {
        return assignmentflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.ASSIGNMENTFLAG
     *
     * @param assignmentflag the value for STM_FIN_INFO.ASSIGNMENTFLAG
     *
     * @mbg.generated
     */
    public void setAssignmentflag(String assignmentflag) {
        this.assignmentflag = assignmentflag == null ? null : assignmentflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.SUBLETTINGFLAG
     *
     * @return the value of STM_FIN_INFO.SUBLETTINGFLAG
     *
     * @mbg.generated
     */
    public String getSublettingflag() {
        return sublettingflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.SUBLETTINGFLAG
     *
     * @param sublettingflag the value for STM_FIN_INFO.SUBLETTINGFLAG
     *
     * @mbg.generated
     */
    public void setSublettingflag(String sublettingflag) {
        this.sublettingflag = sublettingflag == null ? null : sublettingflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CYCLEDAY
     *
     * @return the value of STM_FIN_INFO.CYCLEDAY
     *
     * @mbg.generated
     */
    public String getCycleday() {
        return cycleday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CYCLEDAY
     *
     * @param cycleday the value for STM_FIN_INFO.CYCLEDAY
     *
     * @mbg.generated
     */
    public void setCycleday(String cycleday) {
        this.cycleday = cycleday == null ? null : cycleday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.REDEEMFLAG
     *
     * @return the value of STM_FIN_INFO.REDEEMFLAG
     *
     * @mbg.generated
     */
    public String getRedeemflag() {
        return redeemflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.REDEEMFLAG
     *
     * @param redeemflag the value for STM_FIN_INFO.REDEEMFLAG
     *
     * @mbg.generated
     */
    public void setRedeemflag(String redeemflag) {
        this.redeemflag = redeemflag == null ? null : redeemflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.JHONLYFLAG
     *
     * @return the value of STM_FIN_INFO.JHONLYFLAG
     *
     * @mbg.generated
     */
    public String getJhonlyflag() {
        return jhonlyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.JHONLYFLAG
     *
     * @param jhonlyflag the value for STM_FIN_INFO.JHONLYFLAG
     *
     * @mbg.generated
     */
    public void setJhonlyflag(String jhonlyflag) {
        this.jhonlyflag = jhonlyflag == null ? null : jhonlyflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.MODEL_COMMENT2
     *
     * @return the value of STM_FIN_INFO.MODEL_COMMENT2
     *
     * @mbg.generated
     */
    public String getModelComment2() {
        return modelComment2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.MODEL_COMMENT2
     *
     * @param modelComment2 the value for STM_FIN_INFO.MODEL_COMMENT2
     *
     * @mbg.generated
     */
    public void setModelComment2(String modelComment2) {
        this.modelComment2 = modelComment2 == null ? null : modelComment2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_FIN_INFO.CYCYLESTATUS
     *
     * @return the value of STM_FIN_INFO.CYCYLESTATUS
     *
     * @mbg.generated
     */
    public String getCycylestatus() {
        return cycylestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_FIN_INFO.CYCYLESTATUS
     *
     * @param cycylestatus the value for STM_FIN_INFO.CYCYLESTATUS
     *
     * @mbg.generated
     */
    public void setCycylestatus(String cycylestatus) {
        this.cycylestatus = cycylestatus == null ? null : cycylestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cashFlag=").append(cashFlag);
        sb.append(", channels=").append(channels);
        sb.append(", clientGroups=").append(clientGroups);
        sb.append(", closeTime=").append(closeTime);
        sb.append(", controlFlag=").append(controlFlag);
        sb.append(", controlFlag2=").append(controlFlag2);
        sb.append(", convFlag=").append(convFlag);
        sb.append(", currType=").append(currType);
        sb.append(", cycleCfmdate=").append(cycleCfmdate);
        sb.append(", cycleOpenend=").append(cycleOpenend);
        sb.append(", cycleOpenstart=").append(cycleOpenstart);
        sb.append(", dirFreeDate=").append(dirFreeDate);
        sb.append(", divDays=").append(divDays);
        sb.append(", divMode=").append(divMode);
        sb.append(", divModes=").append(divModes);
        sb.append(", endDate=").append(endDate);
        sb.append(", estabDate=").append(estabDate);
        sb.append(", faceValue=").append(faceValue);
        sb.append(", failDays=").append(failDays);
        sb.append(", guestRate=").append(guestRate);
        sb.append(", incomeDate=").append(incomeDate);
        sb.append(", incomeEnddate=").append(incomeEnddate);
        sb.append(", instAllow=").append(instAllow);
        sb.append(", interestDays=").append(interestDays);
        sb.append(", ipoEndDate=").append(ipoEndDate);
        sb.append(", ipoStartDate=").append(ipoStartDate);
        sb.append(", isCyclePrd=").append(isCyclePrd);
        sb.append(", isNewCust=").append(isNewCust);
        sb.append(", issPrice=").append(issPrice);
        sb.append(", lastDate=").append(lastDate);
        sb.append(", modelComment=").append(modelComment);
        sb.append(", nav=").append(nav);
        sb.append(", nextCycleCfmdate=").append(nextCycleCfmdate);
        sb.append(", nextCycleEnddate=").append(nextCycleEnddate);
        sb.append(", nextCycleOpenend=").append(nextCycleOpenend);
        sb.append(", nextCycleOpenstart=").append(nextCycleOpenstart);
        sb.append(", nextCycleStartdate=").append(nextCycleStartdate);
        sb.append(", nextDate=").append(nextDate);
        sb.append(", oappAmt=").append(oappAmt);
        sb.append(", ofirstAmt=").append(ofirstAmt);
        sb.append(", omaxAccamt=").append(omaxAccamt);
        sb.append(", omaxAmt=").append(omaxAmt);
        sb.append(", omaxRed=").append(omaxRed);
        sb.append(", ominConvvol=").append(ominConvvol);
        sb.append(", ominHold=").append(ominHold);
        sb.append(", ominInvestAmt=").append(ominInvestAmt);
        sb.append(", ominRed=").append(ominRed);
        sb.append(", openTime=").append(openTime);
        sb.append(", osubUnit=").append(osubUnit);
        sb.append(", osurplusLimit=").append(osurplusLimit);
        sb.append(", pappAmt=").append(pappAmt);
        sb.append(", perAllow=").append(perAllow);
        sb.append(", pfirstAmt=").append(pfirstAmt);
        sb.append(", pmaxAccamt=").append(pmaxAccamt);
        sb.append(", pmaxAmt=").append(pmaxAmt);
        sb.append(", pmaxRed=").append(pmaxRed);
        sb.append(", pminConvvol=").append(pminConvvol);
        sb.append(", pminHold=").append(pminHold);
        sb.append(", pminInvestAmt=").append(pminInvestAmt);
        sb.append(", pminRed=").append(pminRed);
        sb.append(", prdAttr=").append(prdAttr);
        sb.append(", prdCode=").append(prdCode);
        sb.append(", prdManager=").append(prdManager);
        sb.append(", prdMaxBala=").append(prdMaxBala);
        sb.append(", prdMinBala=").append(prdMinBala);
        sb.append(", prdName=").append(prdName);
        sb.append(", prdScale=").append(prdScale);
        sb.append(", prdSponsor=").append(prdSponsor);
        sb.append(", prdTemplate=").append(prdTemplate);
        sb.append(", prdTrustee=").append(prdTrustee);
        sb.append(", prdType=").append(prdType);
        sb.append(", prdTypeTjyh=").append(prdTypeTjyh);
        sb.append(", protocolName=").append(protocolName);
        sb.append(", psubUnit=").append(psubUnit);
        sb.append(", psurplusLimit=").append(psurplusLimit);
        sb.append(", redDays=").append(redDays);
        sb.append(", refundDays=").append(refundDays);
        sb.append(", riskLevel=").append(riskLevel);
        sb.append(", riskName=").append(riskName);
        sb.append(", saleStatus=").append(saleStatus);
        sb.append(", shareClass=").append(shareClass);
        sb.append(", status=").append(status);
        sb.append(", statusName=").append(statusName);
        sb.append(", tacode=").append(tacode);
        sb.append(", totNav=").append(totNav);
        sb.append(", totVol=").append(totVol);
        sb.append(", transWay=").append(transWay);
        sb.append(", typeName=").append(typeName);
        sb.append(", typeNo=").append(typeNo);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", assignmentflag=").append(assignmentflag);
        sb.append(", sublettingflag=").append(sublettingflag);
        sb.append(", cycleday=").append(cycleday);
        sb.append(", redeemflag=").append(redeemflag);
        sb.append(", jhonlyflag=").append(jhonlyflag);
        sb.append(", modelComment2=").append(modelComment2);
        sb.append(", cycylestatus=").append(cycylestatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}