package com.cpw.sqlview.sqlview.pojo;

import java.util.ArrayList;
import java.util.List;

public class StmSerialNumberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public StmSerialNumberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSerialnumber1IsNull() {
            addCriterion("SERIALNUMBER1 is null");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1IsNotNull() {
            addCriterion("SERIALNUMBER1 is not null");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1EqualTo(String value) {
            addCriterion("SERIALNUMBER1 =", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1NotEqualTo(String value) {
            addCriterion("SERIALNUMBER1 <>", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1GreaterThan(String value) {
            addCriterion("SERIALNUMBER1 >", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1GreaterThanOrEqualTo(String value) {
            addCriterion("SERIALNUMBER1 >=", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1LessThan(String value) {
            addCriterion("SERIALNUMBER1 <", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1LessThanOrEqualTo(String value) {
            addCriterion("SERIALNUMBER1 <=", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1Like(String value) {
            addCriterion("SERIALNUMBER1 like", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1NotLike(String value) {
            addCriterion("SERIALNUMBER1 not like", value, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1In(List<String> values) {
            addCriterion("SERIALNUMBER1 in", values, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1NotIn(List<String> values) {
            addCriterion("SERIALNUMBER1 not in", values, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1Between(String value1, String value2) {
            addCriterion("SERIALNUMBER1 between", value1, value2, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber1NotBetween(String value1, String value2) {
            addCriterion("SERIALNUMBER1 not between", value1, value2, "serialnumber1");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2IsNull() {
            addCriterion("SERIALNUMBER2 is null");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2IsNotNull() {
            addCriterion("SERIALNUMBER2 is not null");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2EqualTo(String value) {
            addCriterion("SERIALNUMBER2 =", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2NotEqualTo(String value) {
            addCriterion("SERIALNUMBER2 <>", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2GreaterThan(String value) {
            addCriterion("SERIALNUMBER2 >", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2GreaterThanOrEqualTo(String value) {
            addCriterion("SERIALNUMBER2 >=", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2LessThan(String value) {
            addCriterion("SERIALNUMBER2 <", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2LessThanOrEqualTo(String value) {
            addCriterion("SERIALNUMBER2 <=", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2Like(String value) {
            addCriterion("SERIALNUMBER2 like", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2NotLike(String value) {
            addCriterion("SERIALNUMBER2 not like", value, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2In(List<String> values) {
            addCriterion("SERIALNUMBER2 in", values, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2NotIn(List<String> values) {
            addCriterion("SERIALNUMBER2 not in", values, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2Between(String value1, String value2) {
            addCriterion("SERIALNUMBER2 between", value1, value2, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andSerialnumber2NotBetween(String value1, String value2) {
            addCriterion("SERIALNUMBER2 not between", value1, value2, "serialnumber2");
            return (Criteria) this;
        }

        public Criteria andBspserialIsNull() {
            addCriterion("BSPSERIAL is null");
            return (Criteria) this;
        }

        public Criteria andBspserialIsNotNull() {
            addCriterion("BSPSERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andBspserialEqualTo(String value) {
            addCriterion("BSPSERIAL =", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialNotEqualTo(String value) {
            addCriterion("BSPSERIAL <>", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialGreaterThan(String value) {
            addCriterion("BSPSERIAL >", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialGreaterThanOrEqualTo(String value) {
            addCriterion("BSPSERIAL >=", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialLessThan(String value) {
            addCriterion("BSPSERIAL <", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialLessThanOrEqualTo(String value) {
            addCriterion("BSPSERIAL <=", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialLike(String value) {
            addCriterion("BSPSERIAL like", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialNotLike(String value) {
            addCriterion("BSPSERIAL not like", value, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialIn(List<String> values) {
            addCriterion("BSPSERIAL in", values, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialNotIn(List<String> values) {
            addCriterion("BSPSERIAL not in", values, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialBetween(String value1, String value2) {
            addCriterion("BSPSERIAL between", value1, value2, "bspserial");
            return (Criteria) this;
        }

        public Criteria andBspserialNotBetween(String value1, String value2) {
            addCriterion("BSPSERIAL not between", value1, value2, "bspserial");
            return (Criteria) this;
        }

        public Criteria andTradeCodeIsNull() {
            addCriterion("TRADE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTradeCodeIsNotNull() {
            addCriterion("TRADE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTradeCodeEqualTo(String value) {
            addCriterion("TRADE_CODE =", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotEqualTo(String value) {
            addCriterion("TRADE_CODE <>", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeGreaterThan(String value) {
            addCriterion("TRADE_CODE >", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_CODE >=", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeLessThan(String value) {
            addCriterion("TRADE_CODE <", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeLessThanOrEqualTo(String value) {
            addCriterion("TRADE_CODE <=", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeLike(String value) {
            addCriterion("TRADE_CODE like", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotLike(String value) {
            addCriterion("TRADE_CODE not like", value, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeIn(List<String> values) {
            addCriterion("TRADE_CODE in", values, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotIn(List<String> values) {
            addCriterion("TRADE_CODE not in", values, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeBetween(String value1, String value2) {
            addCriterion("TRADE_CODE between", value1, value2, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeCodeNotBetween(String value1, String value2) {
            addCriterion("TRADE_CODE not between", value1, value2, "tradeCode");
            return (Criteria) this;
        }

        public Criteria andTradeDataIsNull() {
            addCriterion("TRADE_DATA is null");
            return (Criteria) this;
        }

        public Criteria andTradeDataIsNotNull() {
            addCriterion("TRADE_DATA is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDataEqualTo(String value) {
            addCriterion("TRADE_DATA =", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataNotEqualTo(String value) {
            addCriterion("TRADE_DATA <>", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataGreaterThan(String value) {
            addCriterion("TRADE_DATA >", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_DATA >=", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataLessThan(String value) {
            addCriterion("TRADE_DATA <", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataLessThanOrEqualTo(String value) {
            addCriterion("TRADE_DATA <=", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataLike(String value) {
            addCriterion("TRADE_DATA like", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataNotLike(String value) {
            addCriterion("TRADE_DATA not like", value, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataIn(List<String> values) {
            addCriterion("TRADE_DATA in", values, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataNotIn(List<String> values) {
            addCriterion("TRADE_DATA not in", values, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataBetween(String value1, String value2) {
            addCriterion("TRADE_DATA between", value1, value2, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeDataNotBetween(String value1, String value2) {
            addCriterion("TRADE_DATA not between", value1, value2, "tradeData");
            return (Criteria) this;
        }

        public Criteria andTradeData1IsNull() {
            addCriterion("TRADE_DATA1 is null");
            return (Criteria) this;
        }

        public Criteria andTradeData1IsNotNull() {
            addCriterion("TRADE_DATA1 is not null");
            return (Criteria) this;
        }

        public Criteria andTradeData1EqualTo(String value) {
            addCriterion("TRADE_DATA1 =", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1NotEqualTo(String value) {
            addCriterion("TRADE_DATA1 <>", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1GreaterThan(String value) {
            addCriterion("TRADE_DATA1 >", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1GreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_DATA1 >=", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1LessThan(String value) {
            addCriterion("TRADE_DATA1 <", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1LessThanOrEqualTo(String value) {
            addCriterion("TRADE_DATA1 <=", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1Like(String value) {
            addCriterion("TRADE_DATA1 like", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1NotLike(String value) {
            addCriterion("TRADE_DATA1 not like", value, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1In(List<String> values) {
            addCriterion("TRADE_DATA1 in", values, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1NotIn(List<String> values) {
            addCriterion("TRADE_DATA1 not in", values, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1Between(String value1, String value2) {
            addCriterion("TRADE_DATA1 between", value1, value2, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andTradeData1NotBetween(String value1, String value2) {
            addCriterion("TRADE_DATA1 not between", value1, value2, "tradeData1");
            return (Criteria) this;
        }

        public Criteria andRetcodeIsNull() {
            addCriterion("RETCODE is null");
            return (Criteria) this;
        }

        public Criteria andRetcodeIsNotNull() {
            addCriterion("RETCODE is not null");
            return (Criteria) this;
        }

        public Criteria andRetcodeEqualTo(String value) {
            addCriterion("RETCODE =", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotEqualTo(String value) {
            addCriterion("RETCODE <>", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeGreaterThan(String value) {
            addCriterion("RETCODE >", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeGreaterThanOrEqualTo(String value) {
            addCriterion("RETCODE >=", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeLessThan(String value) {
            addCriterion("RETCODE <", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeLessThanOrEqualTo(String value) {
            addCriterion("RETCODE <=", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeLike(String value) {
            addCriterion("RETCODE like", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotLike(String value) {
            addCriterion("RETCODE not like", value, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeIn(List<String> values) {
            addCriterion("RETCODE in", values, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotIn(List<String> values) {
            addCriterion("RETCODE not in", values, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeBetween(String value1, String value2) {
            addCriterion("RETCODE between", value1, value2, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetcodeNotBetween(String value1, String value2) {
            addCriterion("RETCODE not between", value1, value2, "retcode");
            return (Criteria) this;
        }

        public Criteria andRetmsgIsNull() {
            addCriterion("RETMSG is null");
            return (Criteria) this;
        }

        public Criteria andRetmsgIsNotNull() {
            addCriterion("RETMSG is not null");
            return (Criteria) this;
        }

        public Criteria andRetmsgEqualTo(String value) {
            addCriterion("RETMSG =", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotEqualTo(String value) {
            addCriterion("RETMSG <>", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgGreaterThan(String value) {
            addCriterion("RETMSG >", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgGreaterThanOrEqualTo(String value) {
            addCriterion("RETMSG >=", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgLessThan(String value) {
            addCriterion("RETMSG <", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgLessThanOrEqualTo(String value) {
            addCriterion("RETMSG <=", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgLike(String value) {
            addCriterion("RETMSG like", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotLike(String value) {
            addCriterion("RETMSG not like", value, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgIn(List<String> values) {
            addCriterion("RETMSG in", values, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotIn(List<String> values) {
            addCriterion("RETMSG not in", values, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgBetween(String value1, String value2) {
            addCriterion("RETMSG between", value1, value2, "retmsg");
            return (Criteria) this;
        }

        public Criteria andRetmsgNotBetween(String value1, String value2) {
            addCriterion("RETMSG not between", value1, value2, "retmsg");
            return (Criteria) this;
        }

        public Criteria andNote01IsNull() {
            addCriterion("NOTE01 is null");
            return (Criteria) this;
        }

        public Criteria andNote01IsNotNull() {
            addCriterion("NOTE01 is not null");
            return (Criteria) this;
        }

        public Criteria andNote01EqualTo(String value) {
            addCriterion("NOTE01 =", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01NotEqualTo(String value) {
            addCriterion("NOTE01 <>", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01GreaterThan(String value) {
            addCriterion("NOTE01 >", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01GreaterThanOrEqualTo(String value) {
            addCriterion("NOTE01 >=", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01LessThan(String value) {
            addCriterion("NOTE01 <", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01LessThanOrEqualTo(String value) {
            addCriterion("NOTE01 <=", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01Like(String value) {
            addCriterion("NOTE01 like", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01NotLike(String value) {
            addCriterion("NOTE01 not like", value, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01In(List<String> values) {
            addCriterion("NOTE01 in", values, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01NotIn(List<String> values) {
            addCriterion("NOTE01 not in", values, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01Between(String value1, String value2) {
            addCriterion("NOTE01 between", value1, value2, "note01");
            return (Criteria) this;
        }

        public Criteria andNote01NotBetween(String value1, String value2) {
            addCriterion("NOTE01 not between", value1, value2, "note01");
            return (Criteria) this;
        }

        public Criteria andTradeNameIsNull() {
            addCriterion("TRADE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTradeNameIsNotNull() {
            addCriterion("TRADE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTradeNameEqualTo(String value) {
            addCriterion("TRADE_NAME =", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameNotEqualTo(String value) {
            addCriterion("TRADE_NAME <>", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameGreaterThan(String value) {
            addCriterion("TRADE_NAME >", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameGreaterThanOrEqualTo(String value) {
            addCriterion("TRADE_NAME >=", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameLessThan(String value) {
            addCriterion("TRADE_NAME <", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameLessThanOrEqualTo(String value) {
            addCriterion("TRADE_NAME <=", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameLike(String value) {
            addCriterion("TRADE_NAME like", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameNotLike(String value) {
            addCriterion("TRADE_NAME not like", value, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameIn(List<String> values) {
            addCriterion("TRADE_NAME in", values, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameNotIn(List<String> values) {
            addCriterion("TRADE_NAME not in", values, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameBetween(String value1, String value2) {
            addCriterion("TRADE_NAME between", value1, value2, "tradeName");
            return (Criteria) this;
        }

        public Criteria andTradeNameNotBetween(String value1, String value2) {
            addCriterion("TRADE_NAME not between", value1, value2, "tradeName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}