package com.cpw.sqlview.sqlview.pojo;

import java.io.Serializable;

public class StmSerialNumber implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.SERIALNUMBER1
     *
     * @mbg.generated
     */
    private String serialnumber1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.SERIALNUMBER2
     *
     * @mbg.generated
     */
    private String serialnumber2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.BSPSERIAL
     *
     * @mbg.generated
     */
    private String bspserial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.TRADE_CODE
     *
     * @mbg.generated
     */
    private String tradeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.TRADE_DATA
     *
     * @mbg.generated
     */
    private String tradeData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.TRADE_DATA1
     *
     * @mbg.generated
     */
    private String tradeData1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.RETCODE
     *
     * @mbg.generated
     */
    private String retcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.RETMSG
     *
     * @mbg.generated
     */
    private String retmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.NOTE01
     *
     * @mbg.generated
     */
    private String note01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STM_SERIAL_NUMBER.TRADE_NAME
     *
     * @mbg.generated
     */
    private String tradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.SERIALNUMBER1
     *
     * @return the value of STM_SERIAL_NUMBER.SERIALNUMBER1
     *
     * @mbg.generated
     */
    public String getSerialnumber1() {
        return serialnumber1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.SERIALNUMBER1
     *
     * @param serialnumber1 the value for STM_SERIAL_NUMBER.SERIALNUMBER1
     *
     * @mbg.generated
     */
    public void setSerialnumber1(String serialnumber1) {
        this.serialnumber1 = serialnumber1 == null ? null : serialnumber1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.SERIALNUMBER2
     *
     * @return the value of STM_SERIAL_NUMBER.SERIALNUMBER2
     *
     * @mbg.generated
     */
    public String getSerialnumber2() {
        return serialnumber2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.SERIALNUMBER2
     *
     * @param serialnumber2 the value for STM_SERIAL_NUMBER.SERIALNUMBER2
     *
     * @mbg.generated
     */
    public void setSerialnumber2(String serialnumber2) {
        this.serialnumber2 = serialnumber2 == null ? null : serialnumber2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.BSPSERIAL
     *
     * @return the value of STM_SERIAL_NUMBER.BSPSERIAL
     *
     * @mbg.generated
     */
    public String getBspserial() {
        return bspserial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.BSPSERIAL
     *
     * @param bspserial the value for STM_SERIAL_NUMBER.BSPSERIAL
     *
     * @mbg.generated
     */
    public void setBspserial(String bspserial) {
        this.bspserial = bspserial == null ? null : bspserial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.TRADE_CODE
     *
     * @return the value of STM_SERIAL_NUMBER.TRADE_CODE
     *
     * @mbg.generated
     */
    public String getTradeCode() {
        return tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.TRADE_CODE
     *
     * @param tradeCode the value for STM_SERIAL_NUMBER.TRADE_CODE
     *
     * @mbg.generated
     */
    public void setTradeCode(String tradeCode) {
        this.tradeCode = tradeCode == null ? null : tradeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.TRADE_DATA
     *
     * @return the value of STM_SERIAL_NUMBER.TRADE_DATA
     *
     * @mbg.generated
     */
    public String getTradeData() {
        return tradeData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.TRADE_DATA
     *
     * @param tradeData the value for STM_SERIAL_NUMBER.TRADE_DATA
     *
     * @mbg.generated
     */
    public void setTradeData(String tradeData) {
        this.tradeData = tradeData == null ? null : tradeData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.TRADE_DATA1
     *
     * @return the value of STM_SERIAL_NUMBER.TRADE_DATA1
     *
     * @mbg.generated
     */
    public String getTradeData1() {
        return tradeData1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.TRADE_DATA1
     *
     * @param tradeData1 the value for STM_SERIAL_NUMBER.TRADE_DATA1
     *
     * @mbg.generated
     */
    public void setTradeData1(String tradeData1) {
        this.tradeData1 = tradeData1 == null ? null : tradeData1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.RETCODE
     *
     * @return the value of STM_SERIAL_NUMBER.RETCODE
     *
     * @mbg.generated
     */
    public String getRetcode() {
        return retcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.RETCODE
     *
     * @param retcode the value for STM_SERIAL_NUMBER.RETCODE
     *
     * @mbg.generated
     */
    public void setRetcode(String retcode) {
        this.retcode = retcode == null ? null : retcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.RETMSG
     *
     * @return the value of STM_SERIAL_NUMBER.RETMSG
     *
     * @mbg.generated
     */
    public String getRetmsg() {
        return retmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.RETMSG
     *
     * @param retmsg the value for STM_SERIAL_NUMBER.RETMSG
     *
     * @mbg.generated
     */
    public void setRetmsg(String retmsg) {
        this.retmsg = retmsg == null ? null : retmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.NOTE01
     *
     * @return the value of STM_SERIAL_NUMBER.NOTE01
     *
     * @mbg.generated
     */
    public String getNote01() {
        return note01;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.NOTE01
     *
     * @param note01 the value for STM_SERIAL_NUMBER.NOTE01
     *
     * @mbg.generated
     */
    public void setNote01(String note01) {
        this.note01 = note01 == null ? null : note01.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STM_SERIAL_NUMBER.TRADE_NAME
     *
     * @return the value of STM_SERIAL_NUMBER.TRADE_NAME
     *
     * @mbg.generated
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STM_SERIAL_NUMBER.TRADE_NAME
     *
     * @param tradeName the value for STM_SERIAL_NUMBER.TRADE_NAME
     *
     * @mbg.generated
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName == null ? null : tradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serialnumber1=").append(serialnumber1);
        sb.append(", serialnumber2=").append(serialnumber2);
        sb.append(", bspserial=").append(bspserial);
        sb.append(", tradeCode=").append(tradeCode);
        sb.append(", tradeData=").append(tradeData);
        sb.append(", tradeData1=").append(tradeData1);
        sb.append(", retcode=").append(retcode);
        sb.append(", retmsg=").append(retmsg);
        sb.append(", note01=").append(note01);
        sb.append(", tradeName=").append(tradeName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}