package com.cpw.sqlview.sqlview.dao;

import com.cpw.sqlview.sqlview.pojo.StmDeviceinfo;
import com.cpw.sqlview.sqlview.pojo.StmDeviceinfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StmDeviceinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    long countByExample(StmDeviceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int deleteByExample(StmDeviceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int insert(StmDeviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int insertSelective(StmDeviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    List<StmDeviceinfo> selectByExample(StmDeviceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    StmDeviceinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StmDeviceinfo record, @Param("example") StmDeviceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StmDeviceinfo record, @Param("example") StmDeviceinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StmDeviceinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_DEVICEINFO
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StmDeviceinfo record);
}