package com.cpw.sqlview.sqlview.dao;

import com.cpw.sqlview.sqlview.pojo.StmFinInfo;
import com.cpw.sqlview.sqlview.pojo.StmFinInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StmFinInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    long countByExample(StmFinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    int deleteByExample(StmFinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    int insert(StmFinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    int insertSelective(StmFinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    List<StmFinInfo> selectByExample(StmFinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StmFinInfo record, @Param("example") StmFinInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_FIN_INFO
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StmFinInfo record, @Param("example") StmFinInfoExample example);
}