package com.cpw.sqlview.sqlview.dao;

import com.cpw.sqlview.sqlview.pojo.StmSerialNumber;
import com.cpw.sqlview.sqlview.pojo.StmSerialNumberExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StmSerialNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    long countByExample(StmSerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    int deleteByExample(StmSerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    int insert(StmSerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    int insertSelective(StmSerialNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    List<StmSerialNumber> selectByExample(StmSerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StmSerialNumber record, @Param("example") StmSerialNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table STM_SERIAL_NUMBER
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StmSerialNumber record, @Param("example") StmSerialNumberExample example);
}